pages:
  image: node:latest
  stage: deploy
  environment:
    name: gitlab-pages
    VUE_APP_STANDALONE_URL: gwvt.gitlab.io/thirteen-vue-standalone/
  script:
    - npm install --progress=false
    # - npm ci
    - npm run build
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
  artifacts:
    paths:
      - public
  only:
    - master
